// Generated by create-api-home — live runmoa Storefront config (pub key only, browser-safe).
window.RUNMOA = {
  "useApi": true,
  "siteHost": "ojiccareer.runmoa.com",
  "storefrontKey": "moa_pub_a3iRqsexkRdBUCPPrTA63xQyWY8jFHxvgrBoDni9yZ-IXKR9pjYHQKXj9_4d8f8h",
  "limit": 48
};
